### ISSUE TITLE
[Feature Request] Desperately needs OPML handling

### ISSUE THREAD

**Issue by SMylk** [DidierHoarau/feedwatcher#48]
As of this now in this form it's not that usable.
Needs to handle at least opml import to test further functionality.

**Comment by DidierHoarau** [comment]
Hi,

That sounds like a good idea. This is something that I will try to implement.

Thanks

**Comment by DidierHoarau** [comment]
Started working on the update. The import is working but now working on the export.

**Comment by DidierHoarau** [comment]
The import/export of OPML is now available in the new version. Thank you for your feature request.
